from pathlib import Path

p = Path("index.html")
s = p.read_text(encoding="utf-8")
start = s.index('<section id="produtos"')
end = s.index('<section id="parceiros"', start)

new = '''<section id="produtos" class="bg-ink py-20 sm:py-28 reveal"><div class="mx-auto w-full max-w-[1160px] px-5"><header class="mx-auto max-w-2xl text-center"><span class="text-xs font-bold uppercase tracking-[0.14em] text-cool">Prova técnica</span><h2 class="mt-3 text-3xl font-extrabold tracking-tight text-panel sm:text-4xl">Tecnologia ConectWeb em ação</h2><p class="mt-4 text-base leading-relaxed text-panel/60">Produtos próprios, integrações reais e software construído para operações que precisam escalar.</p></header><div class="mt-14 grid gap-6 md:grid-cols-3 md:mt-20">
<article class="overflow-hidden rounded-3xl border border-white/10 bg-panel"><div class="border-b border-panel-line bg-panel-muted/70 px-5 py-4"><span class="text-xs font-bold uppercase tracking-[0.12em] text-cool">Produto próprio · IA</span><h3 class="mt-1 text-lg font-extrabold text-ink">Lívia</h3><p class="mt-1 text-sm text-steel">Recepcionista inteligente com IA para o WhatsApp</p></div><div class="min-h-[260px] bg-panel px-5 py-5"><div class="rounded-2xl border border-panel-line bg-panel-muted/50 p-4"><div class="flex items-center gap-3 border-b border-panel-line pb-3"><span class="flex h-9 w-9 items-center justify-center rounded-full bg-cool text-sm font-bold text-white">L</span><div><p class="text-sm font-bold text-ink">Lívia</p><p class="text-xs text-steel">Atendimento com IA</p></div><span class="ml-auto h-2.5 w-2.5 rounded-full bg-success"></span></div><div class="space-y-3 pt-4"><div class="max-w-[88%] rounded-2xl rounded-tl-md bg-panel px-3 py-2 text-xs text-ink">Olá! Como posso ajudar?</div><div class="ml-auto max-w-[82%] rounded-2xl rounded-tr-md bg-cool/10 px-3 py-2 text-xs text-ink">Quero agendar um atendimento</div><div class="max-w-[88%] rounded-2xl rounded-tl-md bg-panel px-3 py-2 text-xs text-ink">Claro. Vou verificar os horários disponíveis.</div></div></div></div></article>
<article class="overflow-hidden rounded-3xl border border-white/10 bg-panel"><div class="border-b border-panel-line bg-panel-muted/70 px-5 py-4"><span class="text-xs font-bold uppercase tracking-[0.12em] text-cool">Automação · Nuvemshop</span><h3 class="mt-1 text-lg font-extrabold text-ink">Nuvem Rush</h3><p class="mt-1 text-sm text-steel">Automações de pedidos, WhatsApp e pós-venda</p></div><div class="min-h-[260px] bg-panel px-5 py-5"><div class="rounded-2xl border border-panel-line bg-panel-muted/50 p-4"><div class="flex items-center justify-between"><span class="text-sm font-bold text-ink">Fluxo de pedidos</span><span class="rounded-full bg-success/10 px-2 py-1 text-[10px] font-semibold text-success">Ativo</span></div><div class="mt-5 space-y-3"><div class="rounded-xl border border-cool/25 bg-panel px-3 py-2 text-xs font-semibold text-ink">Nuvemshop · Pedido pago</div><div class="ml-5 h-4 border-l border-panel-line"></div><div class="rounded-xl border border-panel-line bg-panel px-3 py-2 text-xs font-semibold text-ink">WhatsApp · Confirmação</div><div class="ml-5 h-4 border-l border-panel-line"></div><div class="rounded-xl border border-panel-line bg-panel px-3 py-2 text-xs font-semibold text-ink">E-mail · Pós-venda</div></div></div></div></article>
<article class="overflow-hidden rounded-3xl border border-white/10 bg-panel"><div class="border-b border-panel-line bg-panel-muted/70 px-5 py-4"><span class="text-xs font-bold uppercase tracking-[0.12em] text-cool">Sistema · Revendas de veículos</span><h3 class="mt-1 text-lg font-extrabold text-ink">Financer Auto</h3><p class="mt-1 text-sm text-steel">Gestão de contratos, parcelas e cobrança</p></div><div class="min-h-[260px] bg-panel px-5 py-5"><div class="rounded-2xl border border-panel-line bg-panel-muted/50 p-4"><p class="text-sm font-bold text-ink">Carteira de contratos</p><p class="mt-1 text-xs text-steel">Acompanhamento financeiro</p><div class="mt-5 grid grid-cols-3 gap-2"><div class="rounded-xl border border-panel-line bg-panel p-3"><span class="block text-[10px] text-steel">Em dia</span><strong class="mt-1 block text-lg text-success">72%</strong></div><div class="rounded-xl border border-panel-line bg-panel p-3"><span class="block text-[10px] text-steel">Pendente</span><strong class="mt-1 block text-lg text-warning">19%</strong></div><div class="rounded-xl border border-panel-line bg-panel p-3"><span class="block text-[10px] text-steel">Atraso</span><strong class="mt-1 block text-lg text-danger">9%</strong></div></div></div></div></article>
</div><ul class="mt-12 flex flex-wrap justify-center gap-x-10 gap-y-5 md:mt-14"><li class="text-center"><span class="block text-sm font-bold tracking-tight text-panel">Lívia</span><span class="mt-1 block text-xs text-panel/55">Produto próprio</span></li><li class="text-center"><span class="block text-sm font-bold tracking-tight text-panel">Nuvem Rush</span><span class="mt-1 block text-xs text-panel/55">Em homologação</span></li><li class="text-center"><span class="block text-sm font-bold tracking-tight text-panel">Financer Auto</span><span class="mt-1 block text-xs text-panel/55">Produto próprio</span></li></ul><div class="mt-12 flex justify-center"><a href="/projetos/" class="inline-flex items-center gap-2 rounded-xl border border-white/15 px-6 py-3 text-sm font-semibold text-panel transition-colors hover:border-cool/50 hover:bg-white/5">Ver todos os projetos <span aria-hidden="true">→</span></a></div></div></section>
'''

s = s[:start] + new + s[end:]
for term in ("Lucro ML", "Meu bairro", "Interdição na Av. Central", "Feira livre no Centro", "Padaria do Zé", "Coleta seletiva", "Questão 9 de 20", "Sequência lógica", "Cidade Conectada", "Desafio Lógico"):
    assert term not in s, f"referência restante: {term}"
assert all(term in s for term in ("Lívia", "Nuvem Rush", "Financer Auto"))
p.write_text(s, encoding="utf-8")
